# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
#   sqlc-gen-better-python v0.4.5
from __future__ import annotations

__all__: collections.abc.Sequence[str] = (
    "AttributeStatusesRow",
    "EvalJobRowsRow",
    "LockBuildRowRow",
    "QueryResults",
    "attach_build_to_pr",
    "attribute_status_list",
    "attribute_statuses",
    "backfill_pr_author",
    "bump_build_status",
    "complete_attribute",
    "create_build",
    "create_failed_build",
    "detach_build_from_pr",
    "effect_run_by_context",
    "effects_for_build",
    "effects_for_run",
    "eval_job_rows",
    "find_completed_eval",
    "find_reusable_build",
    "finish_effect",
    "get_build",
    "get_effect_run",
    "lock_build_identity",
    "lock_build_row",
    "mark_attribute_building",
    "mark_eval_completed",
    "record_attributes",
    "set_build_status",
    "set_eval_warnings",
    "settle_unfinished_attributes",
    "start_effect",
    "start_effect_run",
    "start_pending_effects",
)

import dataclasses
import datetime
import operator
import typing

if typing.TYPE_CHECKING:
    import asyncpg
    import asyncpg.cursor
    import collections.abc

    QueryResultsArgsType: typing.TypeAlias = int | float | str | memoryview | datetime.date | datetime.time | datetime.datetime | datetime.timedelta | collections.abc.Sequence[typing.Any] | None

    ConnectionLike: typing.TypeAlias = asyncpg.Connection[asyncpg.Record] | asyncpg.pool.PoolConnectionProxy[asyncpg.Record]

from nixbot.db_gen import models


@dataclasses.dataclass()
class AttributeStatusesRow:
    attr: str
    status: str


@dataclasses.dataclass()
class EvalJobRowsRow:
    attr: str
    system: str | None
    drv_path: str | None
    outputs: str | None


@dataclasses.dataclass()
class LockBuildRowRow:
    id: int
    status: str
    status_generation: int


ATTACH_BUILD_TO_PR: typing.Final[str] = """-- name: AttachBuildToPr :one
UPDATE builds SET pr_number = $2, pr_author = $3 WHERE id = $1 RETURNING id, project_id, number, tree_hash, commit_sha, branch, pr_number, pr_author, status, status_generation, effects_started, error, created_at, started_at, finished_at, eval_warnings, eval_completed, effects_commit_sha, effects_branch, effects_pr_number, eval_key
"""

ATTRIBUTE_STATUS_LIST: typing.Final[str] = """-- name: AttributeStatusList :many
SELECT status FROM build_attributes WHERE build_id = $1
"""

ATTRIBUTE_STATUSES: typing.Final[str] = """-- name: AttributeStatuses :many
SELECT attr, status FROM build_attributes WHERE build_id = $1
"""

BACKFILL_PR_AUTHOR: typing.Final[str] = """-- name: BackfillPrAuthor :one
UPDATE builds SET pr_author = $2 WHERE id = $1 RETURNING id, project_id, number, tree_hash, commit_sha, branch, pr_number, pr_author, status, status_generation, effects_started, error, created_at, started_at, finished_at, eval_warnings, eval_completed, effects_commit_sha, effects_branch, effects_pr_number, eval_key
"""

BUMP_BUILD_STATUS: typing.Final[str] = """-- name: BumpBuildStatus :one
UPDATE builds
SET status = $2,
    status_generation = status_generation + 1,
    finished_at = COALESCE(finished_at, now())
WHERE id = $1
RETURNING status_generation
"""

COMPLETE_ATTRIBUTE: typing.Final[str] = """-- name: CompleteAttribute :exec
WITH attr AS (
    INSERT INTO build_attributes
        (build_id, attr, system, drv_path, outputs, status, error,
         cached, finished_at)
    VALUES ($1, $2, $3, $4, $11::jsonb, $5, $6, $7, now())
    ON CONFLICT (build_id, attr) DO UPDATE SET
        status = EXCLUDED.status,
        -- Eval recorded the full outputs map (multi-output drvs);
        -- merge the freshly-known "out" path into it instead of
        -- replacing it, and never NULL an existing map when no out
        -- path is known.
        outputs = CASE
            WHEN EXCLUDED.outputs IS NULL
                THEN build_attributes.outputs
            ELSE COALESCE(build_attributes.outputs, '{}'::jsonb)
                || EXCLUDED.outputs
        END,
        error = EXCLUDED.error,
        cached = EXCLUDED.cached,
        finished_at = now()
    WHERE NOT $12::boolean
        OR build_attributes.status IN ('pending', 'building')
    RETURNING build_attributes.id
), dropped AS (
    -- Reruns rewrite the same log file; replace the metadata row
    -- instead of accumulating duplicates.
    DELETE FROM logs WHERE attribute_id IN (SELECT attr.id FROM attr)
      AND $8::text IS NOT NULL
)
INSERT INTO logs (attribute_id, path, size_bytes, truncated)
SELECT attr.id, $8, $9::bigint,
       $10::boolean
FROM attr WHERE $8::text IS NOT NULL
"""

CREATE_BUILD: typing.Final[str] = """-- name: CreateBuild :one
WITH n AS (
    UPDATE projects SET next_build_number = next_build_number + 1
    WHERE id = $1::bigint
    RETURNING next_build_number - 1 AS number
)
INSERT INTO builds (project_id, number, tree_hash, eval_key, commit_sha,
                    branch, pr_number, pr_author)
SELECT $1::bigint, n.number, $2::text,
       $3::text, $4::text, $5::text,
       $6::bigint, $7::text
FROM n
RETURNING id, project_id, number, tree_hash, commit_sha, branch, pr_number, pr_author, status, status_generation, effects_started, error, created_at, started_at, finished_at, eval_warnings, eval_completed, effects_commit_sha, effects_branch, effects_pr_number, eval_key
"""

CREATE_FAILED_BUILD: typing.Final[str] = """-- name: CreateFailedBuild :one
WITH n AS (
    UPDATE projects SET next_build_number = next_build_number + 1
    WHERE id = $1::bigint
    RETURNING next_build_number - 1 AS number
)
INSERT INTO builds (project_id, number, commit_sha, branch,
                    pr_number, pr_author, status, error, finished_at)
SELECT $1::bigint, n.number, $2::text,
       $3::text, $4::bigint,
       $5::text, 'failed', $6::text, now()
FROM n
RETURNING id, project_id, number, tree_hash, commit_sha, branch, pr_number, pr_author, status, status_generation, effects_started, error, created_at, started_at, finished_at, eval_warnings, eval_completed, effects_commit_sha, effects_branch, effects_pr_number, eval_key
"""

DETACH_BUILD_FROM_PR: typing.Final[str] = """-- name: DetachBuildFromPr :one
UPDATE builds SET pr_number = NULL, pr_author = NULL,
    branch = CASE WHEN $2::bigint IS NULL
             THEN $3 ELSE branch END
WHERE id = $1 RETURNING id, project_id, number, tree_hash, commit_sha, branch, pr_number, pr_author, status, status_generation, effects_started, error, created_at, started_at, finished_at, eval_warnings, eval_completed, effects_commit_sha, effects_branch, effects_pr_number, eval_key
"""

EFFECT_RUN_BY_CONTEXT: typing.Final[str] = """-- name: EffectRunByContext :one
SELECT id FROM build_effect_runs
WHERE build_id = $1::bigint
  AND branch = $2::text
  AND pr_number = COALESCE($3::bigint, 0)
"""

EFFECTS_FOR_BUILD: typing.Final[str] = """-- name: EffectsForBuild :many
SELECT id, build_id, name, status, error, log_path, log_size, log_truncated, started_at, finished_at, run_id FROM build_effects WHERE build_id = $1 ORDER BY name
"""

EFFECTS_FOR_RUN: typing.Final[str] = """-- name: EffectsForRun :many
SELECT id, build_id, name, status, error, log_path, log_size, log_truncated, started_at, finished_at, run_id FROM build_effects WHERE run_id = $1 ORDER BY name
"""

EVAL_JOB_ROWS: typing.Final[str] = """-- name: EvalJobRows :many
SELECT attr, system, drv_path, outputs FROM build_attributes
WHERE build_id = $1
"""

FIND_COMPLETED_EVAL: typing.Final[str] = """-- name: FindCompletedEval :one
SELECT id FROM builds WHERE project_id = $1 AND tree_hash = $2
AND eval_key = $3
AND eval_completed AND id <> $4
ORDER BY id DESC LIMIT 1
"""

FIND_REUSABLE_BUILD: typing.Final[str] = """-- name: FindReusableBuild :one
SELECT id, project_id, number, tree_hash, commit_sha, branch, pr_number, pr_author, status, status_generation, effects_started, error, created_at, started_at, finished_at, eval_warnings, eval_completed, effects_commit_sha, effects_branch, effects_pr_number, eval_key FROM builds WHERE project_id = $1 AND tree_hash = $2
AND eval_key = $3
AND status <> 'cancelled' ORDER BY id DESC LIMIT 1
"""

FINISH_EFFECT: typing.Final[str] = """-- name: FinishEffect :exec
UPDATE build_effects SET
    status = $3, error = $6, log_path = $7,
    log_size = $4, log_truncated = $5, finished_at = now()
WHERE build_id = $1 AND name = $2
  AND (
      run_id = $8::bigint
      OR (run_id IS NULL AND $8::bigint IS NULL)
  )
"""

GET_BUILD: typing.Final[str] = """-- name: GetBuild :one
SELECT id, project_id, number, tree_hash, commit_sha, branch, pr_number, pr_author, status, status_generation, effects_started, error, created_at, started_at, finished_at, eval_warnings, eval_completed, effects_commit_sha, effects_branch, effects_pr_number, eval_key FROM builds WHERE id = $1
"""

GET_EFFECT_RUN: typing.Final[str] = """-- name: GetEffectRun :one
SELECT id, build_id, commit_sha, branch, pr_number, created_at FROM build_effect_runs WHERE id = $1
"""

LOCK_BUILD_IDENTITY: typing.Final[str] = """-- name: LockBuildIdentity :exec

SELECT pg_advisory_xact_lock(hashtextextended($1::text, 0))
"""

LOCK_BUILD_ROW: typing.Final[str] = """-- name: LockBuildRow :one
SELECT id, status, status_generation FROM builds WHERE id = $1 FOR UPDATE
"""

MARK_ATTRIBUTE_BUILDING: typing.Final[str] = """-- name: MarkAttributeBuilding :one
INSERT INTO build_attributes
    (build_id, attr, system, drv_path, status, started_at)
VALUES ($1, $2, $3, $4, 'building', now())
ON CONFLICT (build_id, attr) DO UPDATE SET
    status = 'building',
    started_at = now(),
    finished_at = NULL
WHERE build_attributes.status IN ('pending', 'building')
RETURNING attr
"""

MARK_EVAL_COMPLETED: typing.Final[str] = """-- name: MarkEvalCompleted :exec
UPDATE builds SET eval_completed = TRUE WHERE id = $1
"""

RECORD_ATTRIBUTES: typing.Final[str] = """-- name: RecordAttributes :exec
INSERT INTO build_attributes (build_id, attr, system, drv_path, outputs, status)
SELECT $1::bigint, u.attr, u.system, u.drv_path, u.outputs, 'pending'
FROM (SELECT unnest($2::text[]) AS attr,
             unnest($3::text[]) AS system,
             unnest($4::text[]) AS drv_path,
             unnest($5::jsonb[]) AS outputs) u
ON CONFLICT (build_id, attr) DO NOTHING
"""

SET_BUILD_STATUS: typing.Final[str] = """-- name: SetBuildStatus :exec
WITH failed_effects AS (
    UPDATE build_effects SET status = 'failed',
        error = 'build did not succeed', finished_at = now()
    WHERE build_effects.build_id = $4::bigint
      AND build_effects.status = 'pending'
      AND $1::text IN ('failed', 'cancelled')
)
UPDATE builds
SET status = $1,
    error = COALESCE($2, error),
    -- A fresh eval must not show the previous attempt's streamed
    -- warnings.
    eval_warnings = CASE
        WHEN $1 = 'evaluating' THEN NULL
        ELSE eval_warnings
    END,
    -- A fresh eval invalidates the recorded job set until it
    -- completes again.
    eval_completed = CASE
        WHEN $1 = 'evaluating' THEN FALSE
        ELSE eval_completed
    END,
    started_at = CASE
        WHEN started_at IS NULL AND $1 <> 'pending' THEN now()
        ELSE started_at
    END,
    -- Invariant: non-terminal states never carry finished_at, else
    -- reruns show negative durations.
    finished_at = CASE
        WHEN $1 = ANY($3::text[]) THEN now()
        ELSE NULL
    END
WHERE builds.id = $4::bigint
"""

SET_EVAL_WARNINGS: typing.Final[str] = """-- name: SetEvalWarnings :exec
UPDATE builds SET eval_warnings = $2::jsonb WHERE id = $1
"""

SETTLE_UNFINISHED_ATTRIBUTES: typing.Final[str] = """-- name: SettleUnfinishedAttributes :exec
UPDATE build_attributes
SET status = 'cancelled', finished_at = now()
WHERE build_id = $1 AND status IN ('pending', 'building')
"""

START_EFFECT: typing.Final[str] = """-- name: StartEffect :exec
INSERT INTO build_effects (build_id, run_id, name, status)
VALUES ($1, $4::bigint, $2, $3)
ON CONFLICT (run_id, name) WHERE run_id IS NOT NULL DO UPDATE SET
    status = $3, error = NULL, log_path = NULL, log_size = 0,
    log_truncated = FALSE, started_at = now(), finished_at = NULL
"""

START_EFFECT_RUN: typing.Final[str] = """-- name: StartEffectRun :one
WITH inserted AS (
    INSERT INTO build_effect_runs (build_id, commit_sha, branch, pr_number)
    VALUES (
        $1::bigint,
        $2::text,
        $3::text,
        COALESCE($4::bigint, 0)
    )
    ON CONFLICT (build_id, branch, pr_number) DO NOTHING
    RETURNING id
), marked AS (
    UPDATE builds SET effects_started = TRUE,
        effects_commit_sha = $2::text,
        effects_branch = $3::text,
        effects_pr_number = $4::bigint
    WHERE id = $1::bigint
      AND EXISTS (SELECT 1 FROM inserted)
)
SELECT id FROM inserted
"""

START_PENDING_EFFECTS: typing.Final[str] = """-- name: StartPendingEffects :exec
INSERT INTO build_effects (build_id, run_id, name, status)
SELECT $1::bigint, $2::bigint, u.name, 'pending'
FROM unnest($3::text[]) AS u(name)
ON CONFLICT (run_id, name) WHERE run_id IS NOT NULL DO UPDATE SET
    status = 'pending', error = NULL, log_path = NULL, log_size = 0,
    log_truncated = FALSE, started_at = now(), finished_at = NULL
"""


T = typing.TypeVar("T")


class QueryResults(typing.Generic[T]):
    __slots__ = ("_args", "_conn", "_cursor", "_decode_hook", "_iterator", "_sql")

    def __init__(
        self,
        conn: ConnectionLike,
        sql: str,
        decode_hook: collections.abc.Callable[[asyncpg.Record], T],
        *args: QueryResultsArgsType,
    ) -> None:
        self._conn = conn
        self._sql = sql
        self._decode_hook = decode_hook
        self._args = args
        self._cursor: asyncpg.cursor.CursorFactory[asyncpg.Record] | None = None
        self._iterator: asyncpg.cursor.CursorIterator[asyncpg.Record] | None = None

    def __aiter__(self) -> QueryResults[T]:
        return self

    def __await__(
        self,
    ) -> collections.abc.Generator[None, None, collections.abc.Sequence[T]]:
        async def _wrapper() -> collections.abc.Sequence[T]:
            result = await self._conn.fetch(self._sql, *self._args)
            return [self._decode_hook(row) for row in result]
        return _wrapper().__await__()

    async def __anext__(self) -> T:
        if self._cursor is None or self._iterator is None:
            self._cursor = self._conn.cursor(self._sql, *self._args)
            self._iterator = self._cursor.__aiter__()
        try:
            record = await self._iterator.__anext__()
        except StopAsyncIteration:
            self._cursor = None
            self._iterator = None
            raise
        return self._decode_hook(record)


async def attach_build_to_pr(conn: ConnectionLike, *, id_: int, pr_number: int | None, pr_author: str | None) -> models.Build | None:
    row = await conn.fetchrow(ATTACH_BUILD_TO_PR, id_, pr_number, pr_author)
    if row is None:
        return None
    return models.Build(id=row[0], project_id=row[1], number=row[2], tree_hash=row[3], commit_sha=row[4], branch=row[5], pr_number=row[6], pr_author=row[7], status=row[8], status_generation=row[9], effects_started=row[10], error=row[11], created_at=row[12], started_at=row[13], finished_at=row[14], eval_warnings=row[15], eval_completed=row[16], effects_commit_sha=row[17], effects_branch=row[18], effects_pr_number=row[19], eval_key=row[20])


def attribute_status_list(conn: ConnectionLike, *, build_id: int) -> QueryResults[str]:
    return QueryResults[str](conn, ATTRIBUTE_STATUS_LIST, operator.itemgetter(0), build_id)


def attribute_statuses(conn: ConnectionLike, *, build_id: int) -> QueryResults[AttributeStatusesRow]:
    def _decode_hook(row: asyncpg.Record) -> AttributeStatusesRow:
        return AttributeStatusesRow(attr=row[0], status=row[1])
    return QueryResults[AttributeStatusesRow](conn, ATTRIBUTE_STATUSES, _decode_hook, build_id)


async def backfill_pr_author(conn: ConnectionLike, *, id_: int, pr_author: str | None) -> models.Build | None:
    row = await conn.fetchrow(BACKFILL_PR_AUTHOR, id_, pr_author)
    if row is None:
        return None
    return models.Build(id=row[0], project_id=row[1], number=row[2], tree_hash=row[3], commit_sha=row[4], branch=row[5], pr_number=row[6], pr_author=row[7], status=row[8], status_generation=row[9], effects_started=row[10], error=row[11], created_at=row[12], started_at=row[13], finished_at=row[14], eval_warnings=row[15], eval_completed=row[16], effects_commit_sha=row[17], effects_branch=row[18], effects_pr_number=row[19], eval_key=row[20])


async def bump_build_status(conn: ConnectionLike, *, id_: int, status: str) -> int | None:
    row = await conn.fetchrow(BUMP_BUILD_STATUS, id_, status)
    if row is None:
        return None
    return row[0]


async def complete_attribute(conn: ConnectionLike, *, build_id: int, attr: str, system: str | None, drv_path: str | None, status: str, error: str | None, cached: bool, log_path: str | None, log_size: int, log_truncated: bool, outputs: str | None, if_unfinished: bool) -> None:
    await conn.execute(COMPLETE_ATTRIBUTE, build_id, attr, system, drv_path, status, error, cached, log_path, log_size, log_truncated, outputs, if_unfinished)


async def create_build(conn: ConnectionLike, *, project_id: int, tree_hash: str | None, eval_key: str, commit_sha: str, branch: str, pr_number: int | None, pr_author: str | None) -> models.Build | None:
    row = await conn.fetchrow(CREATE_BUILD, project_id, tree_hash, eval_key, commit_sha, branch, pr_number, pr_author)
    if row is None:
        return None
    return models.Build(id=row[0], project_id=row[1], number=row[2], tree_hash=row[3], commit_sha=row[4], branch=row[5], pr_number=row[6], pr_author=row[7], status=row[8], status_generation=row[9], effects_started=row[10], error=row[11], created_at=row[12], started_at=row[13], finished_at=row[14], eval_warnings=row[15], eval_completed=row[16], effects_commit_sha=row[17], effects_branch=row[18], effects_pr_number=row[19], eval_key=row[20])


async def create_failed_build(conn: ConnectionLike, *, project_id: int, commit_sha: str, branch: str, pr_number: int | None, pr_author: str | None, error: str | None) -> models.Build | None:
    row = await conn.fetchrow(CREATE_FAILED_BUILD, project_id, commit_sha, branch, pr_number, pr_author, error)
    if row is None:
        return None
    return models.Build(id=row[0], project_id=row[1], number=row[2], tree_hash=row[3], commit_sha=row[4], branch=row[5], pr_number=row[6], pr_author=row[7], status=row[8], status_generation=row[9], effects_started=row[10], error=row[11], created_at=row[12], started_at=row[13], finished_at=row[14], eval_warnings=row[15], eval_completed=row[16], effects_commit_sha=row[17], effects_branch=row[18], effects_pr_number=row[19], eval_key=row[20])


async def detach_build_from_pr(conn: ConnectionLike, *, id_: int, pr_number: int | None, branch: str) -> models.Build | None:
    row = await conn.fetchrow(DETACH_BUILD_FROM_PR, id_, pr_number, branch)
    if row is None:
        return None
    return models.Build(id=row[0], project_id=row[1], number=row[2], tree_hash=row[3], commit_sha=row[4], branch=row[5], pr_number=row[6], pr_author=row[7], status=row[8], status_generation=row[9], effects_started=row[10], error=row[11], created_at=row[12], started_at=row[13], finished_at=row[14], eval_warnings=row[15], eval_completed=row[16], effects_commit_sha=row[17], effects_branch=row[18], effects_pr_number=row[19], eval_key=row[20])


async def effect_run_by_context(conn: ConnectionLike, *, build_id: int, branch: str, pr_number: int | None) -> int | None:
    row = await conn.fetchrow(EFFECT_RUN_BY_CONTEXT, build_id, branch, pr_number)
    if row is None:
        return None
    return row[0]


def effects_for_build(conn: ConnectionLike, *, build_id: int) -> QueryResults[models.BuildEffect]:
    def _decode_hook(row: asyncpg.Record) -> models.BuildEffect:
        return models.BuildEffect(id=row[0], build_id=row[1], name=row[2], status=row[3], error=row[4], log_path=row[5], log_size=row[6], log_truncated=row[7], started_at=row[8], finished_at=row[9], run_id=row[10])
    return QueryResults[models.BuildEffect](conn, EFFECTS_FOR_BUILD, _decode_hook, build_id)


def effects_for_run(conn: ConnectionLike, *, run_id: int | None) -> QueryResults[models.BuildEffect]:
    def _decode_hook(row: asyncpg.Record) -> models.BuildEffect:
        return models.BuildEffect(id=row[0], build_id=row[1], name=row[2], status=row[3], error=row[4], log_path=row[5], log_size=row[6], log_truncated=row[7], started_at=row[8], finished_at=row[9], run_id=row[10])
    return QueryResults[models.BuildEffect](conn, EFFECTS_FOR_RUN, _decode_hook, run_id)


def eval_job_rows(conn: ConnectionLike, *, build_id: int) -> QueryResults[EvalJobRowsRow]:
    def _decode_hook(row: asyncpg.Record) -> EvalJobRowsRow:
        return EvalJobRowsRow(attr=row[0], system=row[1], drv_path=row[2], outputs=row[3])
    return QueryResults[EvalJobRowsRow](conn, EVAL_JOB_ROWS, _decode_hook, build_id)


async def find_completed_eval(conn: ConnectionLike, *, project_id: int, tree_hash: str | None, eval_key: str, exclude_build_id: int) -> int | None:
    row = await conn.fetchrow(FIND_COMPLETED_EVAL, project_id, tree_hash, eval_key, exclude_build_id)
    if row is None:
        return None
    return row[0]


async def find_reusable_build(conn: ConnectionLike, *, project_id: int, tree_hash: str | None, eval_key: str) -> models.Build | None:
    row = await conn.fetchrow(FIND_REUSABLE_BUILD, project_id, tree_hash, eval_key)
    if row is None:
        return None
    return models.Build(id=row[0], project_id=row[1], number=row[2], tree_hash=row[3], commit_sha=row[4], branch=row[5], pr_number=row[6], pr_author=row[7], status=row[8], status_generation=row[9], effects_started=row[10], error=row[11], created_at=row[12], started_at=row[13], finished_at=row[14], eval_warnings=row[15], eval_completed=row[16], effects_commit_sha=row[17], effects_branch=row[18], effects_pr_number=row[19], eval_key=row[20])


async def finish_effect(conn: ConnectionLike, *, build_id: int, name: str, status: str, log_size: int, log_truncated: bool, error: str | None, log_path: str | None, run_id: int | None) -> None:
    await conn.execute(FINISH_EFFECT, build_id, name, status, log_size, log_truncated, error, log_path, run_id)


async def get_build(conn: ConnectionLike, *, id_: int) -> models.Build | None:
    row = await conn.fetchrow(GET_BUILD, id_)
    if row is None:
        return None
    return models.Build(id=row[0], project_id=row[1], number=row[2], tree_hash=row[3], commit_sha=row[4], branch=row[5], pr_number=row[6], pr_author=row[7], status=row[8], status_generation=row[9], effects_started=row[10], error=row[11], created_at=row[12], started_at=row[13], finished_at=row[14], eval_warnings=row[15], eval_completed=row[16], effects_commit_sha=row[17], effects_branch=row[18], effects_pr_number=row[19], eval_key=row[20])


async def get_effect_run(conn: ConnectionLike, *, id_: int) -> models.BuildEffectRun | None:
    row = await conn.fetchrow(GET_EFFECT_RUN, id_)
    if row is None:
        return None
    return models.BuildEffectRun(id=row[0], build_id=row[1], commit_sha=row[2], branch=row[3], pr_number=row[4], created_at=row[5])


async def lock_build_identity(conn: ConnectionLike, *, key: str) -> typing.Any:
    await conn.execute(LOCK_BUILD_IDENTITY, key)


async def lock_build_row(conn: ConnectionLike, *, id_: int) -> LockBuildRowRow | None:
    row = await conn.fetchrow(LOCK_BUILD_ROW, id_)
    if row is None:
        return None
    return LockBuildRowRow(id=row[0], status=row[1], status_generation=row[2])


async def mark_attribute_building(conn: ConnectionLike, *, build_id: int, attr: str, system: str | None, drv_path: str | None) -> str | None:
    row = await conn.fetchrow(MARK_ATTRIBUTE_BUILDING, build_id, attr, system, drv_path)
    if row is None:
        return None
    return row[0]


async def mark_eval_completed(conn: ConnectionLike, *, id_: int) -> None:
    await conn.execute(MARK_EVAL_COMPLETED, id_)


async def record_attributes(conn: ConnectionLike, *, build_id: int, attrs: collections.abc.Sequence[str], systems: collections.abc.Sequence[str], drv_paths: collections.abc.Sequence[str], outputs: collections.abc.Sequence[str]) -> None:
    await conn.execute(RECORD_ATTRIBUTES, build_id, attrs, systems, drv_paths, outputs)


async def set_build_status(conn: ConnectionLike, *, status: str, error: str | None, terminal: collections.abc.Sequence[str], id_: int) -> None:
    await conn.execute(SET_BUILD_STATUS, status, error, terminal, id_)


async def set_eval_warnings(conn: ConnectionLike, *, id_: int, warnings: str) -> None:
    await conn.execute(SET_EVAL_WARNINGS, id_, warnings)


async def settle_unfinished_attributes(conn: ConnectionLike, *, build_id: int) -> None:
    await conn.execute(SETTLE_UNFINISHED_ATTRIBUTES, build_id)


async def start_effect(conn: ConnectionLike, *, build_id: int, name: str, status: str, run_id: int | None) -> None:
    await conn.execute(START_EFFECT, build_id, name, status, run_id)


async def start_effect_run(conn: ConnectionLike, *, build_id: int, commit_sha: str, branch: str, pr_number: int | None) -> int | None:
    row = await conn.fetchrow(START_EFFECT_RUN, build_id, commit_sha, branch, pr_number)
    if row is None:
        return None
    return row[0]


async def start_pending_effects(conn: ConnectionLike, *, build_id: int, run_id: int, names: collections.abc.Sequence[str]) -> None:
    await conn.execute(START_PENDING_EFFECTS, build_id, run_id, names)
