# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
#   sqlc-gen-better-python v0.4.5
from __future__ import annotations

__all__: collections.abc.Sequence[str] = (
    "FailedBuildByDrvRow",
    "QueryResults",
    "clear_failed_status",
    "failed_build_by_drv",
    "failed_status_names",
    "prune_old_failed_builds",
    "prune_old_failed_statuses",
    "upsert_failed_build",
    "upsert_failed_status",
)

import dataclasses
import datetime
import operator
import typing

if typing.TYPE_CHECKING:
    import asyncpg
    import asyncpg.cursor
    import collections.abc

    QueryResultsArgsType: typing.TypeAlias = int | float | str | memoryview | datetime.date | datetime.time | datetime.datetime | datetime.timedelta | collections.abc.Sequence[typing.Any] | None

    ConnectionLike: typing.TypeAlias = asyncpg.Connection[asyncpg.Record] | asyncpg.pool.PoolConnectionProxy[asyncpg.Record]

from nixbot.db_gen import models


@dataclasses.dataclass()
class FailedBuildByDrvRow:
    derivation: str
    timestamp: float
    url: str


CLEAR_FAILED_STATUS: typing.Final[str] = """-- name: ClearFailedStatus :exec
DELETE FROM failed_statuses WHERE revision = $1 AND status_name = $2
"""

FAILED_BUILD_BY_DRV: typing.Final[str] = """-- name: FailedBuildByDrv :one

SELECT derivation, timestamp, url FROM failed_builds
WHERE project_id = $1 AND derivation = $2
"""

FAILED_STATUS_NAMES: typing.Final[str] = """-- name: FailedStatusNames :many
SELECT status_name FROM failed_statuses WHERE revision = $1
"""

PRUNE_OLD_FAILED_BUILDS: typing.Final[str] = """-- name: PruneOldFailedBuilds :exec
DELETE FROM failed_builds
WHERE to_timestamp(timestamp) < now() - make_interval(days => $1::int)
"""

PRUNE_OLD_FAILED_STATUSES: typing.Final[str] = """-- name: PruneOldFailedStatuses :exec
DELETE FROM failed_statuses
WHERE to_timestamp(timestamp) < now() - make_interval(days => $1::int)
"""

UPSERT_FAILED_BUILD: typing.Final[str] = """-- name: UpsertFailedBuild :exec
INSERT INTO failed_builds (project_id, derivation, timestamp, url)
VALUES ($1, $2, $3, $4)
ON CONFLICT (project_id, derivation)
DO UPDATE SET timestamp = EXCLUDED.timestamp, url = EXCLUDED.url
"""

UPSERT_FAILED_STATUS: typing.Final[str] = """-- name: UpsertFailedStatus :exec
INSERT INTO failed_statuses (revision, status_name, timestamp)
VALUES ($1, $2, $3)
ON CONFLICT (revision, status_name)
DO UPDATE SET timestamp = EXCLUDED.timestamp
"""


T = typing.TypeVar("T")


class QueryResults(typing.Generic[T]):
    __slots__ = ("_args", "_conn", "_cursor", "_decode_hook", "_iterator", "_sql")

    def __init__(
        self,
        conn: ConnectionLike,
        sql: str,
        decode_hook: collections.abc.Callable[[asyncpg.Record], T],
        *args: QueryResultsArgsType,
    ) -> None:
        self._conn = conn
        self._sql = sql
        self._decode_hook = decode_hook
        self._args = args
        self._cursor: asyncpg.cursor.CursorFactory[asyncpg.Record] | None = None
        self._iterator: asyncpg.cursor.CursorIterator[asyncpg.Record] | None = None

    def __aiter__(self) -> QueryResults[T]:
        return self

    def __await__(
        self,
    ) -> collections.abc.Generator[None, None, collections.abc.Sequence[T]]:
        async def _wrapper() -> collections.abc.Sequence[T]:
            result = await self._conn.fetch(self._sql, *self._args)
            return [self._decode_hook(row) for row in result]
        return _wrapper().__await__()

    async def __anext__(self) -> T:
        if self._cursor is None or self._iterator is None:
            self._cursor = self._conn.cursor(self._sql, *self._args)
            self._iterator = self._cursor.__aiter__()
        try:
            record = await self._iterator.__anext__()
        except StopAsyncIteration:
            self._cursor = None
            self._iterator = None
            raise
        return self._decode_hook(record)


async def clear_failed_status(conn: ConnectionLike, *, revision: str, status_name: str) -> None:
    await conn.execute(CLEAR_FAILED_STATUS, revision, status_name)


async def failed_build_by_drv(conn: ConnectionLike, *, project_id: int, derivation: str) -> FailedBuildByDrvRow | None:
    row = await conn.fetchrow(FAILED_BUILD_BY_DRV, project_id, derivation)
    if row is None:
        return None
    return FailedBuildByDrvRow(derivation=row[0], timestamp=row[1], url=row[2])


def failed_status_names(conn: ConnectionLike, *, revision: str) -> QueryResults[str]:
    return QueryResults[str](conn, FAILED_STATUS_NAMES, operator.itemgetter(0), revision)


async def prune_old_failed_builds(conn: ConnectionLike, *, retention_days: int) -> None:
    await conn.execute(PRUNE_OLD_FAILED_BUILDS, retention_days)


async def prune_old_failed_statuses(conn: ConnectionLike, *, retention_days: int) -> None:
    await conn.execute(PRUNE_OLD_FAILED_STATUSES, retention_days)


async def upsert_failed_build(conn: ConnectionLike, *, project_id: int, derivation: str, timestamp: float, url: str) -> None:
    await conn.execute(UPSERT_FAILED_BUILD, project_id, derivation, timestamp, url)


async def upsert_failed_status(conn: ConnectionLike, *, revision: str, status_name: str, timestamp: float) -> None:
    await conn.execute(UPSERT_FAILED_STATUS, revision, status_name, timestamp)
