# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
#   sqlc-gen-better-python v0.4.5
from __future__ import annotations

__all__: collections.abc.Sequence[str] = (
    "AttributesForBuildsRow",
    "CleanupOldRowsRow",
    "QueryResults",
    "SucceededAttributeOutputsRow",
    "all_build_ids",
    "attribute_known",
    "attributes_for_builds",
    "cancel_attribute",
    "cancel_build",
    "cleanup_old_rows",
    "commit_built",
    "count_unfinished_attributes",
    "delete_attributes_by_name",
    "drop_removed_effects",
    "effect_status",
    "fail_interrupted_effects",
    "fail_interrupted_scheduled_runs",
    "find_unfinished_builds",
    "project_has_builds",
    "reset_build_for_restart",
    "reset_effects_state",
    "reset_eval_for_reeval",
    "running_build_ids",
    "succeeded_attribute_outputs",
    "supersede_pending_changes",
)

import dataclasses
import datetime
import operator
import typing

if typing.TYPE_CHECKING:
    import asyncpg
    import asyncpg.cursor
    import collections.abc

    QueryResultsArgsType: typing.TypeAlias = int | float | str | memoryview | datetime.date | datetime.time | datetime.datetime | datetime.timedelta | collections.abc.Sequence[typing.Any] | None

    ConnectionLike: typing.TypeAlias = asyncpg.Connection[asyncpg.Record] | asyncpg.pool.PoolConnectionProxy[asyncpg.Record]

from nixbot.db_gen import models


@dataclasses.dataclass()
class AttributesForBuildsRow:
    build_id: int
    attr: str
    system: str | None
    drv_path: str | None
    outputs: str | None
    status: str


@dataclasses.dataclass()
class CleanupOldRowsRow:
    kind: str
    id: int


@dataclasses.dataclass()
class SucceededAttributeOutputsRow:
    attr: str
    outputs: str | None


ALL_BUILD_IDS: typing.Final[str] = """-- name: AllBuildIds :many
SELECT id FROM builds
"""

ATTRIBUTE_KNOWN: typing.Final[str] = """-- name: AttributeKnown :one

SELECT 1 AS one FROM build_attributes WHERE build_id = $1 AND attr = $2
"""

ATTRIBUTES_FOR_BUILDS: typing.Final[str] = """-- name: AttributesForBuilds :many
SELECT build_id, attr, system, drv_path, outputs, status
FROM build_attributes WHERE build_id = ANY($1::bigint[])
"""

CANCEL_ATTRIBUTE: typing.Final[str] = """-- name: CancelAttribute :execrows
UPDATE build_attributes SET status = 'cancelled', finished_at = now()
WHERE build_id = $1 AND attr = $2 AND status IN ('pending', 'building')
"""

CANCEL_BUILD: typing.Final[str] = """-- name: CancelBuild :one
WITH cancelled AS (
    UPDATE builds SET status = 'cancelled', finished_at = now(),
        status_generation = status_generation + 1
    WHERE builds.id = $1 AND builds.status IN ('pending', 'evaluating', 'building')
    RETURNING builds.id, builds.status_generation
), settled AS (
    UPDATE build_attributes SET status = 'cancelled', finished_at = now()
    WHERE build_attributes.build_id IN (SELECT cancelled.id FROM cancelled)
      AND build_attributes.status IN ('pending', 'building')
)
SELECT cancelled.status_generation FROM cancelled
"""

CLEANUP_OLD_ROWS: typing.Final[str] = """-- name: CleanupOldRows :many
WITH del_builds AS (
    DELETE FROM builds
    WHERE finished_at IS NOT NULL
      AND finished_at < now() - make_interval(days => $1::int)
      -- A restarted build keeps its old finished_at until it
      -- re-aggregates; never delete a build that is running again.
      AND status IN ('succeeded', 'failed', 'cancelled')
    RETURNING builds.id
), del_runs AS (
    DELETE FROM scheduled_effect_runs
    WHERE finished_at IS NOT NULL
      AND finished_at < now() - make_interval(days => $1::int)
    RETURNING scheduled_effect_runs.id
), pruned_statuses AS (
    DELETE FROM failed_statuses
    WHERE to_timestamp(timestamp)
        < now() - make_interval(days => $1::int)
), pruned_failures AS (
    DELETE FROM failed_builds
    WHERE to_timestamp(timestamp)
        < now() - make_interval(days => $1::int)
), pruned_check_runs AS (
    DELETE FROM check_runs
    WHERE to_timestamp(timestamp)
        < now() - make_interval(days => $1::int)
)
SELECT 'build' AS kind, del_builds.id FROM del_builds
UNION ALL
SELECT 'scheduled_run' AS kind, del_runs.id FROM del_runs
"""

COMMIT_BUILT: typing.Final[str] = """-- name: CommitBuilt :one
SELECT 1 AS one FROM builds WHERE project_id = $1 AND commit_sha = $2 LIMIT 1
"""

COUNT_UNFINISHED_ATTRIBUTES: typing.Final[str] = """-- name: CountUnfinishedAttributes :one
SELECT count(*) AS count FROM build_attributes
WHERE build_id = $1 AND status IN ('pending', 'building')
"""

DELETE_ATTRIBUTES_BY_NAME: typing.Final[str] = """-- name: DeleteAttributesByName :exec
DELETE FROM build_attributes WHERE build_id = $1
AND attr = ANY($2::text[])
"""

DROP_REMOVED_EFFECTS: typing.Final[str] = """-- name: DropRemovedEffects :exec
DELETE FROM build_effects WHERE run_id = $1::bigint
AND NOT (name = ANY($2::text[]))
"""

EFFECT_STATUS: typing.Final[str] = """-- name: EffectStatus :one
SELECT status FROM build_effects WHERE build_id = $1 AND name = $2
  AND (
      run_id = $3::bigint
      OR (run_id IS NULL AND $3::bigint IS NULL)
  )
"""

FAIL_INTERRUPTED_EFFECTS: typing.Final[str] = """-- name: FailInterruptedEffects :exec
UPDATE build_effects SET status = 'failed',
    error = 'interrupted by a service restart', finished_at = now()
WHERE status = 'running' AND started_at < $1
"""

FAIL_INTERRUPTED_SCHEDULED_RUNS: typing.Final[str] = """-- name: FailInterruptedScheduledRuns :exec
UPDATE scheduled_effect_runs SET status = 'failed',
    error = 'interrupted by a service restart', finished_at = now()
WHERE status = 'running' AND started_at < $1
"""

FIND_UNFINISHED_BUILDS: typing.Final[str] = """-- name: FindUnfinishedBuilds :many
SELECT id, project_id, number, tree_hash, commit_sha, branch, pr_number, pr_author, status, status_generation, effects_started, error, created_at, started_at, finished_at, eval_warnings, eval_completed, effects_commit_sha, effects_branch, effects_pr_number, eval_key FROM builds WHERE status = ANY($1::text[])
AND ($2::bigint IS NULL OR id = $2)
ORDER BY id
"""

PROJECT_HAS_BUILDS: typing.Final[str] = """-- name: ProjectHasBuilds :one
SELECT 1 AS one FROM builds WHERE project_id = $1
AND status != 'cancelled' LIMIT 1
"""

RESET_BUILD_FOR_RESTART: typing.Final[str] = """-- name: ResetBuildForRestart :exec
WITH cleared_failures AS (
    DELETE FROM failed_builds WHERE project_id =
        (SELECT project_id FROM builds
         WHERE builds.id = $2::bigint)
    AND derivation IN
        (SELECT drv_path FROM build_attributes
         WHERE build_id = $2::bigint
           AND ($1::text IS NULL OR attr = $1))
), reset_attrs AS (
    UPDATE build_attributes SET status = 'pending', error = NULL,
        started_at = NULL, finished_at = NULL
    WHERE build_id = $2::bigint
      AND ($1::text IS NULL OR attr = $1)
), delete_effect_runs AS (
    DELETE FROM build_effect_runs
    WHERE build_id = $2::bigint
      AND $1::text IS NULL
), delete_legacy_effect_rows AS (
    DELETE FROM build_effects
    WHERE build_id = $2::bigint
      AND run_id IS NULL
      AND $1::text IS NULL
)
UPDATE builds SET status = 'pending', error = NULL,
    eval_warnings = NULL, started_at = NULL, finished_at = NULL,
    effects_started = CASE WHEN $1::text IS NULL
        THEN FALSE ELSE effects_started END
WHERE builds.id = $2::bigint
"""

RESET_EFFECTS_STATE: typing.Final[str] = """-- name: ResetEffectsState :exec
WITH reset_flag AS (
    UPDATE builds SET effects_started = FALSE WHERE id = $1
), delete_effect_runs AS (
    DELETE FROM build_effect_runs WHERE build_id = $1
)
DELETE FROM build_effects
WHERE build_effects.build_id = $1::bigint AND run_id IS NULL
"""

RESET_EVAL_FOR_REEVAL: typing.Final[str] = """-- name: ResetEvalForReeval :exec
WITH flag AS (
    UPDATE builds SET eval_completed = FALSE WHERE id = $1
)
DELETE FROM build_attributes WHERE build_id = $1
AND (status IN ('pending', 'building') OR drv_path IS NULL)
"""

RUNNING_BUILD_IDS: typing.Final[str] = """-- name: RunningBuildIds :many
SELECT id FROM builds WHERE status IN ('pending', 'evaluating', 'building')
"""

SUCCEEDED_ATTRIBUTE_OUTPUTS: typing.Final[str] = """-- name: SucceededAttributeOutputs :many
SELECT attr, outputs FROM build_attributes
WHERE build_id = $1 AND status IN ('succeeded', 'skipped_local')
"""

SUPERSEDE_PENDING_CHANGES: typing.Final[str] = """-- name: SupersedePendingChanges :exec
UPDATE work_queue SET status = 'done', finished_at = now()
WHERE kind = 'change' AND status = 'pending'
  AND payload->>'forge' = $1::text
  AND payload->>'forge_repo_id' = $2::text
  AND (payload->>'pr_number')::int = $3::int
"""


T = typing.TypeVar("T")


class QueryResults(typing.Generic[T]):
    __slots__ = ("_args", "_conn", "_cursor", "_decode_hook", "_iterator", "_sql")

    def __init__(
        self,
        conn: ConnectionLike,
        sql: str,
        decode_hook: collections.abc.Callable[[asyncpg.Record], T],
        *args: QueryResultsArgsType,
    ) -> None:
        self._conn = conn
        self._sql = sql
        self._decode_hook = decode_hook
        self._args = args
        self._cursor: asyncpg.cursor.CursorFactory[asyncpg.Record] | None = None
        self._iterator: asyncpg.cursor.CursorIterator[asyncpg.Record] | None = None

    def __aiter__(self) -> QueryResults[T]:
        return self

    def __await__(
        self,
    ) -> collections.abc.Generator[None, None, collections.abc.Sequence[T]]:
        async def _wrapper() -> collections.abc.Sequence[T]:
            result = await self._conn.fetch(self._sql, *self._args)
            return [self._decode_hook(row) for row in result]
        return _wrapper().__await__()

    async def __anext__(self) -> T:
        if self._cursor is None or self._iterator is None:
            self._cursor = self._conn.cursor(self._sql, *self._args)
            self._iterator = self._cursor.__aiter__()
        try:
            record = await self._iterator.__anext__()
        except StopAsyncIteration:
            self._cursor = None
            self._iterator = None
            raise
        return self._decode_hook(record)


def all_build_ids(conn: ConnectionLike) -> QueryResults[int]:
    return QueryResults[int](conn, ALL_BUILD_IDS, operator.itemgetter(0))


async def attribute_known(conn: ConnectionLike, *, build_id: int, attr: str) -> int | None:
    row = await conn.fetchrow(ATTRIBUTE_KNOWN, build_id, attr)
    if row is None:
        return None
    return row[0]


def attributes_for_builds(conn: ConnectionLike, *, build_ids: collections.abc.Sequence[int]) -> QueryResults[AttributesForBuildsRow]:
    def _decode_hook(row: asyncpg.Record) -> AttributesForBuildsRow:
        return AttributesForBuildsRow(build_id=row[0], attr=row[1], system=row[2], drv_path=row[3], outputs=row[4], status=row[5])
    return QueryResults[AttributesForBuildsRow](conn, ATTRIBUTES_FOR_BUILDS, _decode_hook, build_ids)


async def cancel_attribute(conn: ConnectionLike, *, build_id: int, attr: str) -> int:
    r = await conn.execute(CANCEL_ATTRIBUTE, build_id, attr)
    return int(n) if (p := r.split()) and (n := p[-1]).isdigit() else 0


async def cancel_build(conn: ConnectionLike, *, id_: int) -> int | None:
    row = await conn.fetchrow(CANCEL_BUILD, id_)
    if row is None:
        return None
    return row[0]


def cleanup_old_rows(conn: ConnectionLike, *, retention_days: int) -> QueryResults[CleanupOldRowsRow]:
    def _decode_hook(row: asyncpg.Record) -> CleanupOldRowsRow:
        return CleanupOldRowsRow(kind=row[0], id=row[1])
    return QueryResults[CleanupOldRowsRow](conn, CLEANUP_OLD_ROWS, _decode_hook, retention_days)


async def commit_built(conn: ConnectionLike, *, project_id: int, commit_sha: str) -> int | None:
    row = await conn.fetchrow(COMMIT_BUILT, project_id, commit_sha)
    if row is None:
        return None
    return row[0]


async def count_unfinished_attributes(conn: ConnectionLike, *, build_id: int) -> int | None:
    row = await conn.fetchrow(COUNT_UNFINISHED_ATTRIBUTES, build_id)
    if row is None:
        return None
    return row[0]


async def delete_attributes_by_name(conn: ConnectionLike, *, build_id: int, attrs: collections.abc.Sequence[str]) -> None:
    await conn.execute(DELETE_ATTRIBUTES_BY_NAME, build_id, attrs)


async def drop_removed_effects(conn: ConnectionLike, *, run_id: int, names: collections.abc.Sequence[str]) -> None:
    await conn.execute(DROP_REMOVED_EFFECTS, run_id, names)


async def effect_status(conn: ConnectionLike, *, build_id: int, name: str, run_id: int | None) -> str | None:
    row = await conn.fetchrow(EFFECT_STATUS, build_id, name, run_id)
    if row is None:
        return None
    return row[0]


async def fail_interrupted_effects(conn: ConnectionLike, *, started_before: datetime.datetime) -> None:
    await conn.execute(FAIL_INTERRUPTED_EFFECTS, started_before)


async def fail_interrupted_scheduled_runs(conn: ConnectionLike, *, started_before: datetime.datetime) -> None:
    await conn.execute(FAIL_INTERRUPTED_SCHEDULED_RUNS, started_before)


def find_unfinished_builds(conn: ConnectionLike, *, statuses: collections.abc.Sequence[str], build_id: int | None) -> QueryResults[models.Build]:
    def _decode_hook(row: asyncpg.Record) -> models.Build:
        return models.Build(id=row[0], project_id=row[1], number=row[2], tree_hash=row[3], commit_sha=row[4], branch=row[5], pr_number=row[6], pr_author=row[7], status=row[8], status_generation=row[9], effects_started=row[10], error=row[11], created_at=row[12], started_at=row[13], finished_at=row[14], eval_warnings=row[15], eval_completed=row[16], effects_commit_sha=row[17], effects_branch=row[18], effects_pr_number=row[19], eval_key=row[20])
    return QueryResults[models.Build](conn, FIND_UNFINISHED_BUILDS, _decode_hook, statuses, build_id)


async def project_has_builds(conn: ConnectionLike, *, project_id: int) -> int | None:
    row = await conn.fetchrow(PROJECT_HAS_BUILDS, project_id)
    if row is None:
        return None
    return row[0]


async def reset_build_for_restart(conn: ConnectionLike, *, attr: str | None, build_id: int) -> None:
    await conn.execute(RESET_BUILD_FOR_RESTART, attr, build_id)


async def reset_effects_state(conn: ConnectionLike, *, build_id: int) -> None:
    await conn.execute(RESET_EFFECTS_STATE, build_id)


async def reset_eval_for_reeval(conn: ConnectionLike, *, build_id: int) -> None:
    await conn.execute(RESET_EVAL_FOR_REEVAL, build_id)


def running_build_ids(conn: ConnectionLike) -> QueryResults[int]:
    return QueryResults[int](conn, RUNNING_BUILD_IDS, operator.itemgetter(0))


def succeeded_attribute_outputs(conn: ConnectionLike, *, build_id: int) -> QueryResults[SucceededAttributeOutputsRow]:
    def _decode_hook(row: asyncpg.Record) -> SucceededAttributeOutputsRow:
        return SucceededAttributeOutputsRow(attr=row[0], outputs=row[1])
    return QueryResults[SucceededAttributeOutputsRow](conn, SUCCEEDED_ATTRIBUTE_OUTPUTS, _decode_hook, build_id)


async def supersede_pending_changes(conn: ConnectionLike, *, forge: str, forge_repo_id: str, pr_number: int) -> None:
    await conn.execute(SUPERSEDE_PENDING_CHANGES, forge, forge_repo_id, pr_number)
