# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
#   sqlc-gen-better-python v0.4.5
from __future__ import annotations

__all__: collections.abc.Sequence[str] = (
    "Build",
    "BuildEffect",
    "BuildEffectRun",
    "Project",
    "ScheduledEffect",
)

import dataclasses
import typing

if typing.TYPE_CHECKING:
    import collections.abc
    import datetime


@dataclasses.dataclass()
class Build:
    id: int
    project_id: int
    number: int
    tree_hash: str | None
    commit_sha: str
    branch: str
    pr_number: int | None
    pr_author: str | None
    status: str
    status_generation: int
    effects_started: bool
    error: str | None
    created_at: datetime.datetime
    started_at: datetime.datetime | None
    finished_at: datetime.datetime | None
    eval_warnings: str | None
    eval_completed: bool
    effects_commit_sha: str | None
    effects_branch: str | None
    effects_pr_number: int | None
    eval_key: str


@dataclasses.dataclass()
class BuildEffect:
    id: int
    build_id: int
    name: str
    status: str
    error: str | None
    log_path: str | None
    log_size: int
    log_truncated: bool
    started_at: datetime.datetime
    finished_at: datetime.datetime | None
    run_id: int | None


@dataclasses.dataclass()
class BuildEffectRun:
    id: int
    build_id: int
    commit_sha: str
    branch: str
    pr_number: int
    created_at: datetime.datetime


@dataclasses.dataclass()
class Project:
    id: int
    forge: str
    forge_repo_id: str
    owner: str
    name: str
    default_branch: str
    url: str
    private: bool
    enabled: bool
    next_build_number: int
    created_at: datetime.datetime
    updated_at: datetime.datetime
    reconcile_watermark: datetime.datetime | None


@dataclasses.dataclass()
class ScheduledEffect:
    project_id: int
    schedule_name: str
    effect: str
    when_spec: str
    last_run: datetime.datetime | None
