# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
#   sqlc-gen-better-python v0.4.5
from __future__ import annotations

__all__: collections.abc.Sequence[str] = (
    "ProjectForgeIdsRow",
    "ProjectVisibilityRowsRow",
    "QueryResults",
    "advance_reconcile_watermark",
    "count_discovered_projects",
    "count_enabled_projects",
    "create_webhook_secret",
    "enabled_projects",
    "project_by_forge_id",
    "project_by_id",
    "project_forge_ids",
    "project_visibility_rows",
    "reconcile_watermark",
    "rotate_webhook_secret",
    "set_project_enabled",
    "toggle_project_enabled",
    "upsert_discovered_projects",
    "upsert_pull_based_projects",
    "webhook_secret",
    "webhook_secret_by_forge_repo",
)

import dataclasses
import datetime
import operator
import typing

if typing.TYPE_CHECKING:
    import asyncpg
    import asyncpg.cursor
    import collections.abc

    QueryResultsArgsType: typing.TypeAlias = int | float | str | memoryview | datetime.date | datetime.time | datetime.datetime | datetime.timedelta | collections.abc.Sequence[typing.Any] | None

    ConnectionLike: typing.TypeAlias = asyncpg.Connection[asyncpg.Record] | asyncpg.pool.PoolConnectionProxy[asyncpg.Record]

from nixbot.db_gen import models


@dataclasses.dataclass()
class ProjectForgeIdsRow:
    id: int
    forge: str
    forge_repo_id: str


@dataclasses.dataclass()
class ProjectVisibilityRowsRow:
    id: int
    forge: str
    forge_repo_id: str
    owner: str
    name: str
    private: bool


ADVANCE_RECONCILE_WATERMARK: typing.Final[str] = """-- name: AdvanceReconcileWatermark :exec
UPDATE projects SET reconcile_watermark = $2 WHERE id = $1
AND (reconcile_watermark IS NULL OR reconcile_watermark < $2)
"""

COUNT_DISCOVERED_PROJECTS: typing.Final[str] = """-- name: CountDiscoveredProjects :one

SELECT count(*) AS count FROM projects WHERE forge <> 'pull_based'
"""

COUNT_ENABLED_PROJECTS: typing.Final[str] = """-- name: CountEnabledProjects :one
SELECT count(*) AS count FROM projects WHERE enabled
"""

CREATE_WEBHOOK_SECRET: typing.Final[str] = """-- name: CreateWebhookSecret :one
INSERT INTO webhook_secrets (project_id, secret)
VALUES ($1, $2)
ON CONFLICT (project_id) DO UPDATE SET secret = webhook_secrets.secret
RETURNING secret
"""

ENABLED_PROJECTS: typing.Final[str] = """-- name: EnabledProjects :many
SELECT id, forge, forge_repo_id, owner, name, default_branch, url, private, enabled, next_build_number, created_at, updated_at, reconcile_watermark FROM projects WHERE enabled ORDER BY owner, name
"""

PROJECT_BY_FORGE_ID: typing.Final[str] = """-- name: ProjectByForgeId :one
SELECT id, forge, forge_repo_id, owner, name, default_branch, url, private, enabled, next_build_number, created_at, updated_at, reconcile_watermark FROM projects WHERE forge = $1 AND forge_repo_id = $2
"""

PROJECT_BY_ID: typing.Final[str] = """-- name: ProjectById :one
SELECT id, forge, forge_repo_id, owner, name, default_branch, url, private, enabled, next_build_number, created_at, updated_at, reconcile_watermark FROM projects WHERE id = $1
"""

PROJECT_FORGE_IDS: typing.Final[str] = """-- name: ProjectForgeIds :many
SELECT id, forge, forge_repo_id FROM projects
"""

PROJECT_VISIBILITY_ROWS: typing.Final[str] = """-- name: ProjectVisibilityRows :many
SELECT id, forge, forge_repo_id, owner, name, private FROM projects
"""

RECONCILE_WATERMARK: typing.Final[str] = """-- name: ReconcileWatermark :one
SELECT reconcile_watermark FROM projects WHERE id = $1
"""

ROTATE_WEBHOOK_SECRET: typing.Final[str] = """-- name: RotateWebhookSecret :one
INSERT INTO webhook_secrets (project_id, secret)
VALUES ($1, $2)
ON CONFLICT (project_id) DO UPDATE SET secret = EXCLUDED.secret
RETURNING secret
"""

SET_PROJECT_ENABLED: typing.Final[str] = """-- name: SetProjectEnabled :exec
UPDATE projects SET enabled = $2, updated_at = now() WHERE id = $1
"""

TOGGLE_PROJECT_ENABLED: typing.Final[str] = """-- name: ToggleProjectEnabled :exec
UPDATE projects SET enabled = NOT enabled, updated_at = now() WHERE id = $1
"""

UPSERT_DISCOVERED_PROJECTS: typing.Final[str] = """-- name: UpsertDiscoveredProjects :exec
INSERT INTO projects
    (forge, forge_repo_id, owner, name, default_branch,
     url, private, enabled)
SELECT u.forge, u.forge_repo_id, u.owner, u.name, u.default_branch,
       u.url, u.private, u.enabled
FROM (SELECT unnest($1::text[]) AS forge,
             unnest($2::text[]) AS forge_repo_id,
             unnest($3::text[]) AS owner,
             unnest($4::text[]) AS name,
             unnest($5::text[]) AS default_branch,
             unnest($6::text[]) AS url,
             unnest($7::boolean[]) AS private,
             unnest($8::boolean[]) AS enabled) u
ON CONFLICT (forge, forge_repo_id) DO UPDATE SET
    owner = EXCLUDED.owner,
    name = EXCLUDED.name,
    default_branch = EXCLUDED.default_branch,
    url = EXCLUDED.url,
    private = EXCLUDED.private,
    updated_at = now()
WHERE (projects.owner, projects.name,
       projects.default_branch, projects.url,
       projects.private)
      IS DISTINCT FROM
      (EXCLUDED.owner, EXCLUDED.name,
       EXCLUDED.default_branch, EXCLUDED.url,
       EXCLUDED.private)
"""

UPSERT_PULL_BASED_PROJECTS: typing.Final[str] = """-- name: UpsertPullBasedProjects :exec
INSERT INTO projects
    (forge, forge_repo_id, owner, name, default_branch,
     url, private, enabled)
SELECT 'pull_based', u.forge_repo_id, u.owner, u.name, u.default_branch,
       u.url, FALSE, TRUE
FROM (SELECT unnest($1::text[]) AS forge_repo_id,
             unnest($2::text[]) AS owner,
             unnest($3::text[]) AS name,
             unnest($4::text[]) AS default_branch,
             unnest($5::text[]) AS url) u
ON CONFLICT (forge, forge_repo_id) DO UPDATE SET
    default_branch = EXCLUDED.default_branch,
    url = EXCLUDED.url,
    updated_at = now()
WHERE (projects.default_branch, projects.url)
      IS DISTINCT FROM
      (EXCLUDED.default_branch, EXCLUDED.url)
"""

WEBHOOK_SECRET: typing.Final[str] = """-- name: WebhookSecret :one
SELECT secret FROM webhook_secrets WHERE project_id = $1
"""

WEBHOOK_SECRET_BY_FORGE_REPO: typing.Final[str] = """-- name: WebhookSecretByForgeRepo :one
SELECT s.secret FROM webhook_secrets s
JOIN projects p ON p.id = s.project_id
WHERE p.forge = $1 AND p.forge_repo_id = $2
"""


T = typing.TypeVar("T")


class QueryResults(typing.Generic[T]):
    __slots__ = ("_args", "_conn", "_cursor", "_decode_hook", "_iterator", "_sql")

    def __init__(
        self,
        conn: ConnectionLike,
        sql: str,
        decode_hook: collections.abc.Callable[[asyncpg.Record], T],
        *args: QueryResultsArgsType,
    ) -> None:
        self._conn = conn
        self._sql = sql
        self._decode_hook = decode_hook
        self._args = args
        self._cursor: asyncpg.cursor.CursorFactory[asyncpg.Record] | None = None
        self._iterator: asyncpg.cursor.CursorIterator[asyncpg.Record] | None = None

    def __aiter__(self) -> QueryResults[T]:
        return self

    def __await__(
        self,
    ) -> collections.abc.Generator[None, None, collections.abc.Sequence[T]]:
        async def _wrapper() -> collections.abc.Sequence[T]:
            result = await self._conn.fetch(self._sql, *self._args)
            return [self._decode_hook(row) for row in result]
        return _wrapper().__await__()

    async def __anext__(self) -> T:
        if self._cursor is None or self._iterator is None:
            self._cursor = self._conn.cursor(self._sql, *self._args)
            self._iterator = self._cursor.__aiter__()
        try:
            record = await self._iterator.__anext__()
        except StopAsyncIteration:
            self._cursor = None
            self._iterator = None
            raise
        return self._decode_hook(record)


async def advance_reconcile_watermark(conn: ConnectionLike, *, id_: int, reconcile_watermark: datetime.datetime | None) -> None:
    await conn.execute(ADVANCE_RECONCILE_WATERMARK, id_, reconcile_watermark)


async def count_discovered_projects(conn: ConnectionLike) -> int | None:
    row = await conn.fetchrow(COUNT_DISCOVERED_PROJECTS)
    if row is None:
        return None
    return row[0]


async def count_enabled_projects(conn: ConnectionLike) -> int | None:
    row = await conn.fetchrow(COUNT_ENABLED_PROJECTS)
    if row is None:
        return None
    return row[0]


async def create_webhook_secret(conn: ConnectionLike, *, project_id: int, secret: str) -> str | None:
    row = await conn.fetchrow(CREATE_WEBHOOK_SECRET, project_id, secret)
    if row is None:
        return None
    return row[0]


def enabled_projects(conn: ConnectionLike) -> QueryResults[models.Project]:
    def _decode_hook(row: asyncpg.Record) -> models.Project:
        return models.Project(id=row[0], forge=row[1], forge_repo_id=row[2], owner=row[3], name=row[4], default_branch=row[5], url=row[6], private=row[7], enabled=row[8], next_build_number=row[9], created_at=row[10], updated_at=row[11], reconcile_watermark=row[12])
    return QueryResults[models.Project](conn, ENABLED_PROJECTS, _decode_hook)


async def project_by_forge_id(conn: ConnectionLike, *, forge: str, forge_repo_id: str) -> models.Project | None:
    row = await conn.fetchrow(PROJECT_BY_FORGE_ID, forge, forge_repo_id)
    if row is None:
        return None
    return models.Project(id=row[0], forge=row[1], forge_repo_id=row[2], owner=row[3], name=row[4], default_branch=row[5], url=row[6], private=row[7], enabled=row[8], next_build_number=row[9], created_at=row[10], updated_at=row[11], reconcile_watermark=row[12])


async def project_by_id(conn: ConnectionLike, *, id_: int) -> models.Project | None:
    row = await conn.fetchrow(PROJECT_BY_ID, id_)
    if row is None:
        return None
    return models.Project(id=row[0], forge=row[1], forge_repo_id=row[2], owner=row[3], name=row[4], default_branch=row[5], url=row[6], private=row[7], enabled=row[8], next_build_number=row[9], created_at=row[10], updated_at=row[11], reconcile_watermark=row[12])


def project_forge_ids(conn: ConnectionLike) -> QueryResults[ProjectForgeIdsRow]:
    def _decode_hook(row: asyncpg.Record) -> ProjectForgeIdsRow:
        return ProjectForgeIdsRow(id=row[0], forge=row[1], forge_repo_id=row[2])
    return QueryResults[ProjectForgeIdsRow](conn, PROJECT_FORGE_IDS, _decode_hook)


def project_visibility_rows(conn: ConnectionLike) -> QueryResults[ProjectVisibilityRowsRow]:
    def _decode_hook(row: asyncpg.Record) -> ProjectVisibilityRowsRow:
        return ProjectVisibilityRowsRow(id=row[0], forge=row[1], forge_repo_id=row[2], owner=row[3], name=row[4], private=row[5])
    return QueryResults[ProjectVisibilityRowsRow](conn, PROJECT_VISIBILITY_ROWS, _decode_hook)


async def reconcile_watermark(conn: ConnectionLike, *, id_: int) -> datetime.datetime | None:
    row = await conn.fetchrow(RECONCILE_WATERMARK, id_)
    if row is None:
        return None
    return row[0]


async def rotate_webhook_secret(conn: ConnectionLike, *, project_id: int, secret: str) -> str | None:
    row = await conn.fetchrow(ROTATE_WEBHOOK_SECRET, project_id, secret)
    if row is None:
        return None
    return row[0]


async def set_project_enabled(conn: ConnectionLike, *, id_: int, enabled: bool) -> None:
    await conn.execute(SET_PROJECT_ENABLED, id_, enabled)


async def toggle_project_enabled(conn: ConnectionLike, *, id_: int) -> None:
    await conn.execute(TOGGLE_PROJECT_ENABLED, id_)


async def upsert_discovered_projects(conn: ConnectionLike, *, forges: collections.abc.Sequence[str], forge_repo_ids: collections.abc.Sequence[str], owners: collections.abc.Sequence[str], names: collections.abc.Sequence[str], default_branches: collections.abc.Sequence[str], urls: collections.abc.Sequence[str], privates: collections.abc.Sequence[bool], enableds: collections.abc.Sequence[bool]) -> None:
    await conn.execute(UPSERT_DISCOVERED_PROJECTS, forges, forge_repo_ids, owners, names, default_branches, urls, privates, enableds)


async def upsert_pull_based_projects(conn: ConnectionLike, *, forge_repo_ids: collections.abc.Sequence[str], owners: collections.abc.Sequence[str], names: collections.abc.Sequence[str], default_branches: collections.abc.Sequence[str], urls: collections.abc.Sequence[str]) -> None:
    await conn.execute(UPSERT_PULL_BASED_PROJECTS, forge_repo_ids, owners, names, default_branches, urls)


async def webhook_secret(conn: ConnectionLike, *, project_id: int) -> str | None:
    row = await conn.fetchrow(WEBHOOK_SECRET, project_id)
    if row is None:
        return None
    return row[0]


async def webhook_secret_by_forge_repo(conn: ConnectionLike, *, forge: str, forge_repo_id: str) -> str | None:
    row = await conn.fetchrow(WEBHOOK_SECRET_BY_FORGE_REPO, forge, forge_repo_id)
    if row is None:
        return None
    return row[0]
