# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
#   sqlc-gen-better-python v0.4.5
from __future__ import annotations

__all__: collections.abc.Sequence[str] = (
    "LatestScheduledRunsRow",
    "ProjectSchedulesRow",
    "QueryResults",
    "ScheduledRunDetailRow",
    "ScheduledRunsForEffectRow",
    "SchedulesForUpdateRow",
    "delete_project_schedules",
    "due_schedule_rows",
    "finish_scheduled_run",
    "insert_schedules",
    "latest_scheduled_runs",
    "mark_schedule_run",
    "project_schedules",
    "scheduled_run_detail",
    "scheduled_run_exists",
    "scheduled_runs_for_effect",
    "schedules_for_update",
    "start_scheduled_run",
)

import dataclasses
import datetime
import operator
import typing

if typing.TYPE_CHECKING:
    import asyncpg
    import asyncpg.cursor
    import collections.abc

    QueryResultsArgsType: typing.TypeAlias = int | float | str | memoryview | datetime.date | datetime.time | datetime.datetime | datetime.timedelta | collections.abc.Sequence[typing.Any] | None

    ConnectionLike: typing.TypeAlias = asyncpg.Connection[asyncpg.Record] | asyncpg.pool.PoolConnectionProxy[asyncpg.Record]

from nixbot.db_gen import models


@dataclasses.dataclass()
class LatestScheduledRunsRow:
    id: int
    schedule_name: str
    effect: str
    status: str
    error: str | None
    started_at: datetime.datetime
    finished_at: datetime.datetime | None


@dataclasses.dataclass()
class ProjectSchedulesRow:
    schedule_name: str
    effect: str
    when_spec: str
    last_run: datetime.datetime | None


@dataclasses.dataclass()
class ScheduledRunDetailRow:
    id: int
    schedule_name: str
    effect: str
    status: str
    error: str | None
    started_at: datetime.datetime
    finished_at: datetime.datetime | None


@dataclasses.dataclass()
class ScheduledRunsForEffectRow:
    id: int
    schedule_name: str
    effect: str
    status: str
    error: str | None
    started_at: datetime.datetime
    finished_at: datetime.datetime | None


@dataclasses.dataclass()
class SchedulesForUpdateRow:
    schedule_name: str
    effect: str
    when_spec: str
    last_run: datetime.datetime | None


DELETE_PROJECT_SCHEDULES: typing.Final[str] = """-- name: DeleteProjectSchedules :exec
DELETE FROM scheduled_effects WHERE project_id = $1
"""

DUE_SCHEDULE_ROWS: typing.Final[str] = """-- name: DueScheduleRows :many
SELECT project_id, schedule_name, effect, when_spec, last_run
FROM scheduled_effects
WHERE last_run IS NULL
   OR last_run < date_trunc('minute', $1::timestamptz)
"""

FINISH_SCHEDULED_RUN: typing.Final[str] = """-- name: FinishScheduledRun :exec
UPDATE scheduled_effect_runs
SET status = $2, error = $3, finished_at = now() WHERE id = $1
"""

INSERT_SCHEDULES: typing.Final[str] = """-- name: InsertSchedules :exec
INSERT INTO scheduled_effects
    (project_id, schedule_name, effect, when_spec, last_run)
SELECT $1::bigint, u.schedule_name, u.effect, u.when_spec,
       u.last_run
FROM (SELECT unnest($2::text[]) AS schedule_name,
             unnest($3::text[]) AS effect,
             unnest($4::jsonb[]) AS when_spec,
             unnest($5::timestamptz[]) AS last_run) u
"""

LATEST_SCHEDULED_RUNS: typing.Final[str] = """-- name: LatestScheduledRuns :many
SELECT DISTINCT ON (schedule_name, effect)
       id, schedule_name, effect, status, error,
       started_at, finished_at
FROM scheduled_effect_runs WHERE project_id = $1
ORDER BY schedule_name, effect, started_at DESC
"""

MARK_SCHEDULE_RUN: typing.Final[str] = """-- name: MarkScheduleRun :exec
UPDATE scheduled_effects SET last_run = $4
WHERE project_id = $1 AND schedule_name = $2 AND effect = $3
"""

PROJECT_SCHEDULES: typing.Final[str] = """-- name: ProjectSchedules :many
SELECT schedule_name, effect, when_spec, last_run
FROM scheduled_effects WHERE project_id = $1
ORDER BY schedule_name, effect
"""

SCHEDULED_RUN_DETAIL: typing.Final[str] = """-- name: ScheduledRunDetail :one
SELECT id, schedule_name, effect, status, error, started_at, finished_at
FROM scheduled_effect_runs WHERE id = $1 AND project_id = $2
"""

SCHEDULED_RUN_EXISTS: typing.Final[str] = """-- name: ScheduledRunExists :one
SELECT id FROM scheduled_effect_runs WHERE id = $1 AND project_id = $2
"""

SCHEDULED_RUNS_FOR_EFFECT: typing.Final[str] = """-- name: ScheduledRunsForEffect :many
SELECT id, schedule_name, effect, status, error, started_at, finished_at
FROM scheduled_effect_runs
WHERE project_id = $1
  AND schedule_name = $2
  AND effect = $3
  AND ($4::bigint IS NULL OR id < $4)
ORDER BY id DESC LIMIT $5::bigint
"""

SCHEDULES_FOR_UPDATE: typing.Final[str] = """-- name: SchedulesForUpdate :many

SELECT schedule_name, effect, when_spec, last_run
FROM scheduled_effects WHERE project_id = $1
"""

START_SCHEDULED_RUN: typing.Final[str] = """-- name: StartScheduledRun :one
INSERT INTO scheduled_effect_runs (project_id, schedule_name, effect)
VALUES ($1, $2, $3) RETURNING id
"""


T = typing.TypeVar("T")


class QueryResults(typing.Generic[T]):
    __slots__ = ("_args", "_conn", "_cursor", "_decode_hook", "_iterator", "_sql")

    def __init__(
        self,
        conn: ConnectionLike,
        sql: str,
        decode_hook: collections.abc.Callable[[asyncpg.Record], T],
        *args: QueryResultsArgsType,
    ) -> None:
        self._conn = conn
        self._sql = sql
        self._decode_hook = decode_hook
        self._args = args
        self._cursor: asyncpg.cursor.CursorFactory[asyncpg.Record] | None = None
        self._iterator: asyncpg.cursor.CursorIterator[asyncpg.Record] | None = None

    def __aiter__(self) -> QueryResults[T]:
        return self

    def __await__(
        self,
    ) -> collections.abc.Generator[None, None, collections.abc.Sequence[T]]:
        async def _wrapper() -> collections.abc.Sequence[T]:
            result = await self._conn.fetch(self._sql, *self._args)
            return [self._decode_hook(row) for row in result]
        return _wrapper().__await__()

    async def __anext__(self) -> T:
        if self._cursor is None or self._iterator is None:
            self._cursor = self._conn.cursor(self._sql, *self._args)
            self._iterator = self._cursor.__aiter__()
        try:
            record = await self._iterator.__anext__()
        except StopAsyncIteration:
            self._cursor = None
            self._iterator = None
            raise
        return self._decode_hook(record)


async def delete_project_schedules(conn: ConnectionLike, *, project_id: int) -> None:
    await conn.execute(DELETE_PROJECT_SCHEDULES, project_id)


def due_schedule_rows(conn: ConnectionLike, *, now: datetime.datetime) -> QueryResults[models.ScheduledEffect]:
    def _decode_hook(row: asyncpg.Record) -> models.ScheduledEffect:
        return models.ScheduledEffect(project_id=row[0], schedule_name=row[1], effect=row[2], when_spec=row[3], last_run=row[4])
    return QueryResults[models.ScheduledEffect](conn, DUE_SCHEDULE_ROWS, _decode_hook, now)


async def finish_scheduled_run(conn: ConnectionLike, *, id_: int, status: str, error: str | None) -> None:
    await conn.execute(FINISH_SCHEDULED_RUN, id_, status, error)


async def insert_schedules(conn: ConnectionLike, *, project_id: int, schedule_names: collections.abc.Sequence[str], effects: collections.abc.Sequence[str], when_specs: collections.abc.Sequence[str], last_runs: collections.abc.Sequence[datetime.datetime]) -> None:
    await conn.execute(INSERT_SCHEDULES, project_id, schedule_names, effects, when_specs, last_runs)


def latest_scheduled_runs(conn: ConnectionLike, *, project_id: int) -> QueryResults[LatestScheduledRunsRow]:
    def _decode_hook(row: asyncpg.Record) -> LatestScheduledRunsRow:
        return LatestScheduledRunsRow(id=row[0], schedule_name=row[1], effect=row[2], status=row[3], error=row[4], started_at=row[5], finished_at=row[6])
    return QueryResults[LatestScheduledRunsRow](conn, LATEST_SCHEDULED_RUNS, _decode_hook, project_id)


async def mark_schedule_run(conn: ConnectionLike, *, project_id: int, schedule_name: str, effect: str, last_run: datetime.datetime | None) -> None:
    await conn.execute(MARK_SCHEDULE_RUN, project_id, schedule_name, effect, last_run)


def project_schedules(conn: ConnectionLike, *, project_id: int) -> QueryResults[ProjectSchedulesRow]:
    def _decode_hook(row: asyncpg.Record) -> ProjectSchedulesRow:
        return ProjectSchedulesRow(schedule_name=row[0], effect=row[1], when_spec=row[2], last_run=row[3])
    return QueryResults[ProjectSchedulesRow](conn, PROJECT_SCHEDULES, _decode_hook, project_id)


async def scheduled_run_detail(conn: ConnectionLike, *, id_: int, project_id: int) -> ScheduledRunDetailRow | None:
    row = await conn.fetchrow(SCHEDULED_RUN_DETAIL, id_, project_id)
    if row is None:
        return None
    return ScheduledRunDetailRow(id=row[0], schedule_name=row[1], effect=row[2], status=row[3], error=row[4], started_at=row[5], finished_at=row[6])


async def scheduled_run_exists(conn: ConnectionLike, *, id_: int, project_id: int) -> int | None:
    row = await conn.fetchrow(SCHEDULED_RUN_EXISTS, id_, project_id)
    if row is None:
        return None
    return row[0]


def scheduled_runs_for_effect(conn: ConnectionLike, *, project_id: int, schedule_name: str, effect: str, before: int | None, limit_: int) -> QueryResults[ScheduledRunsForEffectRow]:
    def _decode_hook(row: asyncpg.Record) -> ScheduledRunsForEffectRow:
        return ScheduledRunsForEffectRow(id=row[0], schedule_name=row[1], effect=row[2], status=row[3], error=row[4], started_at=row[5], finished_at=row[6])
    return QueryResults[ScheduledRunsForEffectRow](conn, SCHEDULED_RUNS_FOR_EFFECT, _decode_hook, project_id, schedule_name, effect, before, limit_)


def schedules_for_update(conn: ConnectionLike, *, project_id: int) -> QueryResults[SchedulesForUpdateRow]:
    def _decode_hook(row: asyncpg.Record) -> SchedulesForUpdateRow:
        return SchedulesForUpdateRow(schedule_name=row[0], effect=row[1], when_spec=row[2], last_run=row[3])
    return QueryResults[SchedulesForUpdateRow](conn, SCHEDULES_FOR_UPDATE, _decode_hook, project_id)


async def start_scheduled_run(conn: ConnectionLike, *, project_id: int, schedule_name: str, effect: str) -> int | None:
    row = await conn.fetchrow(START_SCHEDULED_RUN, project_id, schedule_name, effect)
    if row is None:
        return None
    return row[0]
