# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
#   sqlc-gen-better-python v0.4.5
from __future__ import annotations

__all__: collections.abc.Sequence[str] = (
    "ApiTokenByHashRow",
    "ApiTokensForUserRow",
    "QueryResults",
    "api_token_by_hash",
    "api_tokens_for_user",
    "create_api_token",
    "delete_forge_token",
    "get_forge_token",
    "revoke_api_token",
    "revoke_session",
    "save_forge_token",
    "session_revoked",
)

import dataclasses
import datetime
import operator
import typing

if typing.TYPE_CHECKING:
    import asyncpg
    import asyncpg.cursor
    import collections.abc

    QueryResultsArgsType: typing.TypeAlias = int | float | str | memoryview | datetime.date | datetime.time | datetime.datetime | datetime.timedelta | collections.abc.Sequence[typing.Any] | None

    ConnectionLike: typing.TypeAlias = asyncpg.Connection[asyncpg.Record] | asyncpg.pool.PoolConnectionProxy[asyncpg.Record]

from nixbot.db_gen import models


@dataclasses.dataclass()
class ApiTokenByHashRow:
    user_qualified: str
    expires_at: datetime.datetime | None
    groups: collections.abc.Sequence[str]


@dataclasses.dataclass()
class ApiTokensForUserRow:
    id: int
    name: str
    created_at: datetime.datetime
    expires_at: datetime.datetime | None


API_TOKEN_BY_HASH: typing.Final[str] = """-- name: ApiTokenByHash :one
WITH pruned AS (
    DELETE FROM api_tokens WHERE expires_at < now()
)
SELECT t.user_qualified, t.expires_at, t.groups
FROM api_tokens t WHERE t.token_hash = $1
"""

API_TOKENS_FOR_USER: typing.Final[str] = """-- name: ApiTokensForUser :many
WITH pruned AS (
    DELETE FROM api_tokens WHERE expires_at < now()
)
SELECT t.id, t.name, t.created_at, t.expires_at FROM api_tokens t
WHERE t.user_qualified = $1 ORDER BY t.id
"""

CREATE_API_TOKEN: typing.Final[str] = """-- name: CreateApiToken :exec

INSERT INTO api_tokens (user_qualified, name, token_hash, expires_at, groups)
VALUES ($1, $2, $3, $4, $5)
"""

DELETE_FORGE_TOKEN: typing.Final[str] = """-- name: DeleteForgeToken :exec
DELETE FROM forge_tokens WHERE session_id = $1
"""

GET_FORGE_TOKEN: typing.Final[str] = """-- name: GetForgeToken :one
SELECT token FROM forge_tokens
WHERE session_id = $1 AND expires_at > now()
"""

REVOKE_API_TOKEN: typing.Final[str] = """-- name: RevokeApiToken :one
DELETE FROM api_tokens WHERE id = $1 AND user_qualified = $2 RETURNING id
"""

REVOKE_SESSION: typing.Final[str] = """-- name: RevokeSession :exec
WITH pruned AS (
    DELETE FROM revoked_sessions WHERE expires_at < now()
)
INSERT INTO revoked_sessions (session_id, expires_at)
VALUES ($1, now() + make_interval(secs => $2::float))
ON CONFLICT (session_id) DO UPDATE
    SET expires_at = GREATEST(revoked_sessions.expires_at, EXCLUDED.expires_at)
"""

SAVE_FORGE_TOKEN: typing.Final[str] = """-- name: SaveForgeToken :exec
WITH pruned AS (
    DELETE FROM forge_tokens WHERE expires_at < now()
)
INSERT INTO forge_tokens (session_id, token, expires_at)
VALUES ($1, $2, now() + make_interval(secs => $3::float))
ON CONFLICT (session_id) DO UPDATE
    SET token = EXCLUDED.token, expires_at = EXCLUDED.expires_at
"""

SESSION_REVOKED: typing.Final[str] = """-- name: SessionRevoked :one
SELECT EXISTS(SELECT 1 FROM revoked_sessions WHERE session_id = $1) AS revoked
"""


T = typing.TypeVar("T")


class QueryResults(typing.Generic[T]):
    __slots__ = ("_args", "_conn", "_cursor", "_decode_hook", "_iterator", "_sql")

    def __init__(
        self,
        conn: ConnectionLike,
        sql: str,
        decode_hook: collections.abc.Callable[[asyncpg.Record], T],
        *args: QueryResultsArgsType,
    ) -> None:
        self._conn = conn
        self._sql = sql
        self._decode_hook = decode_hook
        self._args = args
        self._cursor: asyncpg.cursor.CursorFactory[asyncpg.Record] | None = None
        self._iterator: asyncpg.cursor.CursorIterator[asyncpg.Record] | None = None

    def __aiter__(self) -> QueryResults[T]:
        return self

    def __await__(
        self,
    ) -> collections.abc.Generator[None, None, collections.abc.Sequence[T]]:
        async def _wrapper() -> collections.abc.Sequence[T]:
            result = await self._conn.fetch(self._sql, *self._args)
            return [self._decode_hook(row) for row in result]
        return _wrapper().__await__()

    async def __anext__(self) -> T:
        if self._cursor is None or self._iterator is None:
            self._cursor = self._conn.cursor(self._sql, *self._args)
            self._iterator = self._cursor.__aiter__()
        try:
            record = await self._iterator.__anext__()
        except StopAsyncIteration:
            self._cursor = None
            self._iterator = None
            raise
        return self._decode_hook(record)


async def api_token_by_hash(conn: ConnectionLike, *, token_hash: str) -> ApiTokenByHashRow | None:
    row = await conn.fetchrow(API_TOKEN_BY_HASH, token_hash)
    if row is None:
        return None
    return ApiTokenByHashRow(user_qualified=row[0], expires_at=row[1], groups=row[2])


def api_tokens_for_user(conn: ConnectionLike, *, user_qualified: str) -> QueryResults[ApiTokensForUserRow]:
    def _decode_hook(row: asyncpg.Record) -> ApiTokensForUserRow:
        return ApiTokensForUserRow(id=row[0], name=row[1], created_at=row[2], expires_at=row[3])
    return QueryResults[ApiTokensForUserRow](conn, API_TOKENS_FOR_USER, _decode_hook, user_qualified)


async def create_api_token(conn: ConnectionLike, *, user_qualified: str, name: str, token_hash: str, expires_at: datetime.datetime | None, groups: collections.abc.Sequence[str]) -> None:
    await conn.execute(CREATE_API_TOKEN, user_qualified, name, token_hash, expires_at, groups)


async def delete_forge_token(conn: ConnectionLike, *, session_id: str) -> None:
    await conn.execute(DELETE_FORGE_TOKEN, session_id)


async def get_forge_token(conn: ConnectionLike, *, session_id: str) -> str | None:
    row = await conn.fetchrow(GET_FORGE_TOKEN, session_id)
    if row is None:
        return None
    return row[0]


async def revoke_api_token(conn: ConnectionLike, *, id_: int, user_qualified: str) -> int | None:
    row = await conn.fetchrow(REVOKE_API_TOKEN, id_, user_qualified)
    if row is None:
        return None
    return row[0]


async def revoke_session(conn: ConnectionLike, *, session_id: str, lifetime: float) -> None:
    await conn.execute(REVOKE_SESSION, session_id, lifetime)


async def save_forge_token(conn: ConnectionLike, *, session_id: str, token: str, lifetime: float) -> None:
    await conn.execute(SAVE_FORGE_TOKEN, session_id, token, lifetime)


async def session_revoked(conn: ConnectionLike, *, session_id: str) -> bool | None:
    row = await conn.fetchrow(SESSION_REVOKED, session_id)
    if row is None:
        return None
    return row[0]
