# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
#   sqlc-gen-better-python v0.4.5
from __future__ import annotations

__all__: collections.abc.Sequence[str] = (
    "ClaimNextWorkItemRow",
    "claim_next_work_item",
    "cleanup_work_queue",
    "enqueue_effect_items",
    "enqueue_work_item",
    "finish_work_item",
    "settle_interrupted_work",
)

import dataclasses
import datetime
import operator
import typing

if typing.TYPE_CHECKING:
    import asyncpg
    import asyncpg.cursor
    import collections.abc

    QueryResultsArgsType: typing.TypeAlias = int | float | str | memoryview | datetime.date | datetime.time | datetime.datetime | datetime.timedelta | collections.abc.Sequence[typing.Any] | None

    ConnectionLike: typing.TypeAlias = asyncpg.Connection[asyncpg.Record] | asyncpg.pool.PoolConnectionProxy[asyncpg.Record]

from nixbot.db_gen import models


@dataclasses.dataclass()
class ClaimNextWorkItemRow:
    id: int
    kind: str
    dedup_key: str
    payload: str


CLAIM_NEXT_WORK_ITEM: typing.Final[str] = """-- name: ClaimNextWorkItem :one
UPDATE work_queue SET status = 'running', claimed_at = now()
WHERE id = (
    SELECT id FROM work_queue w
    WHERE w.status = 'pending'
      AND NOT EXISTS (
        SELECT 1 FROM work_queue r
        WHERE r.dedup_key = w.dedup_key AND r.status = 'running'
      )
    ORDER BY w.created_at
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
RETURNING id, kind, dedup_key, payload
"""

CLEANUP_WORK_QUEUE: typing.Final[str] = """-- name: CleanupWorkQueue :exec
DELETE FROM work_queue
WHERE finished_at IS NOT NULL
  AND finished_at < now() - make_interval(days => $1::int)
"""

ENQUEUE_EFFECT_ITEMS: typing.Final[str] = """-- name: EnqueueEffectItems :exec
INSERT INTO work_queue (kind, dedup_key, payload)
SELECT 'effect', $1::text,
       jsonb_build_object('build_id', $2::bigint,
                          'name', u.name)
FROM unnest($3::text[]) AS u(name)
ON CONFLICT (kind, dedup_key, md5(payload::text))
WHERE status = 'pending'
DO NOTHING
"""

ENQUEUE_WORK_ITEM: typing.Final[str] = """-- name: EnqueueWorkItem :one

INSERT INTO work_queue (kind, dedup_key, payload)
VALUES ($1, $2, $3::jsonb)
ON CONFLICT (kind, dedup_key, md5(payload::text))
WHERE status = 'pending'
DO NOTHING
RETURNING id
"""

FINISH_WORK_ITEM: typing.Final[str] = """-- name: FinishWorkItem :exec
UPDATE work_queue
SET status = $2, error = $3, finished_at = now()
WHERE id = $1
"""

SETTLE_INTERRUPTED_WORK: typing.Final[str] = """-- name: SettleInterruptedWork :exec
WITH requeued AS (
    UPDATE work_queue w SET status = 'pending', claimed_at = NULL
    WHERE w.status = 'running' AND NOT EXISTS (
        SELECT 1 FROM work_queue p
        WHERE p.kind = w.kind AND p.dedup_key = w.dedup_key
          AND p.status = 'pending'
    )
)
UPDATE work_queue w SET status = 'failed', finished_at = now(),
    error = 'interrupted; superseded by a newer request'
WHERE w.status = 'running' AND EXISTS (
    SELECT 1 FROM work_queue p
    WHERE p.kind = w.kind AND p.dedup_key = w.dedup_key
      AND p.status = 'pending'
)
"""


async def claim_next_work_item(conn: ConnectionLike) -> ClaimNextWorkItemRow | None:
    row = await conn.fetchrow(CLAIM_NEXT_WORK_ITEM)
    if row is None:
        return None
    return ClaimNextWorkItemRow(id=row[0], kind=row[1], dedup_key=row[2], payload=row[3])


async def cleanup_work_queue(conn: ConnectionLike, *, retention_days: int) -> None:
    await conn.execute(CLEANUP_WORK_QUEUE, retention_days)


async def enqueue_effect_items(conn: ConnectionLike, *, dedup_key: str, build_id: int, names: collections.abc.Sequence[str]) -> None:
    await conn.execute(ENQUEUE_EFFECT_ITEMS, dedup_key, build_id, names)


async def enqueue_work_item(conn: ConnectionLike, *, kind: str, dedup_key: str, payload: str) -> int | None:
    row = await conn.fetchrow(ENQUEUE_WORK_ITEM, kind, dedup_key, payload)
    if row is None:
        return None
    return row[0]


async def finish_work_item(conn: ConnectionLike, *, id_: int, status: str, error: str | None) -> None:
    await conn.execute(FINISH_WORK_ITEM, id_, status, error)


async def settle_interrupted_work(conn: ConnectionLike) -> None:
    await conn.execute(SETTLE_INTERRUPTED_WORK)
